In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.4.4


In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-kstykkss/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-kstykkss/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.31.188.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.31.188.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-kstykkss/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-kstykkss/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas config

In [8]:
a = np.zeros(10)
a[5]= 10
print(a)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [11]:
a[5].itemsize

8

In [12]:
print(f'size = {a.size * a.itemsize}')

size = 80


In [17]:
!python -c "import numpy; numpy.info(numpy.arange)"

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [18]:
b = np.arange(12,44)
print(b)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43]


In [20]:
b =b[::-1]
print(b)

[43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20
 19 18 17 16 15 14 13 12]


In [24]:
c = np.arange(9)
print(c)
c=c.reshape(3,3)
print(c)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
d = np.nonzero([0,1,2,0,0,3,0])

print(d)

TypeError: tuple indices must be integers or slices, not tuple

In [29]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
f = np.random.randint(0,10,size=(3,3,4))
print(f)

[[[5 8 4 8]
  [8 6 5 9]
  [0 4 4 8]]

 [[3 5 0 1]
  [6 0 6 6]
  [6 9 7 1]]

 [[6 1 7 1]
  [9 0 4 8]
  [0 5 6 2]]]


In [42]:
g = np.random.randint(1,11,size = (10,10))
max_num,min_num = g.max(),g.min()
print(g)
print(max_num,min_num)

[[ 6  8  2  1  9  7  3  6 10  5]
 [ 7  2  8  8 10  9  5  8  8  4]
 [ 2  4  7  1  9 10  2  2  7  5]
 [10  5  9  9  8 10  7  5  4  9]
 [ 7  3  7  8  8  1  9  5 10  2]
 [ 3 10  2  3  3  9  3  1  6  6]
 [ 5  1 10  5  8  8  4  1  3  8]
 [ 4  6  4  9  6 10  9  3 10  4]
 [ 8  5  7  3 10  7  1  4  5  9]
 [ 3  5  8  5  6  6  9  2  6  9]]
10 1


In [43]:
h = np.arange(30)
h_mean = h.mean()
print(h)
print(h_mean)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
14.5
